name: Deploy to AWS Amplify

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          
      - name: Install dependencies
        run: yarn install
        
      - name: Run lint
        run: yarn lint
        
      - name: Build application
        run: yarn generate
        
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: .output/public

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: .output/public
          
      - name: Deploy to AWS Amplify
        run: |
          # Obtém o ID do aplicativo Amplify
          APP_ID=${{ secrets.AMPLIFY_APP_ID }}
          
          # Obtém o ID da branch (geralmente é main ou master)
          BRANCH_NAME=main
          
          # Compacta os arquivos de build
          zip -r build.zip .output/public
          
          # Faz o upload e implantação para o Amplify
          aws amplify start-deployment \
            --app-id $APP_ID \
            --branch-name $BRANCH_NAME \
            --source-url build.zip \
            --region ${{ secrets.AWS_REGION }}
          
          echo "Deployment iniciado no AWS Amplify" 